"""ResolveKit core module."""

from resolvekit.core.api.resolver import ExplainedResolution
from resolvekit.core.datapack import (
    DataPackLoader,
    DataPackMetadata,
    LoadedDataPack,
)
from resolvekit.core.errors import (
    AmbiguousLinkError,
    AmbiguousResolutionError,
    DataModuleNotFoundError,
    DataPackError,
    DataPackNormalizerVersionError,
    DataPackRuntimeVersionError,
    IncompatibleFeatureSchemaError,
    IncompatibleVersionError,
    InvalidKeyError,
    LinkError,
    MissingModuleDependencyError,
    ModuleConflictError,
    ModuleRegistryError,
    NoModulesInstalledError,
    RegistryError,
    ResolutionError,
    UnknownDomainError,
    UnsupportedStoreError,
)
from resolvekit.core.model import (
    Candidate,
    CandidateEvidence,
    CandidateSummary,
    ConstraintOutcome,
    EntityRecord,
    GenerationContext,
    MatchTier,
    NormalizedText,
    Query,
    ReasonCode,
    RefinementHint,
    ResolutionContext,
    ResolutionResult,
    ResolutionStatus,
    RetrievalSummary,
    ScoreSummary,
    Severity,
)
from resolvekit.core.module_registry import (
    get_module_path,
    list_available_modules,
    register_module,
    unregister_module,
)
from resolvekit.core.registry import (
    DomainPack,
    DomainRegistry,
    default_registry,
    get_pack_factory,
    register_pack_factory,
)
from resolvekit.core.store import EntityStore, SQLiteEntityStore
from resolvekit.core.util.normalization import NormalizationProfile, TextNormalizer

__all__ = [
    "AmbiguousLinkError",
    "AmbiguousResolutionError",
    "Candidate",
    "CandidateEvidence",
    "CandidateSummary",
    "ConstraintOutcome",
    "DataModuleNotFoundError",
    "DataPackError",
    "DataPackLoader",
    "DataPackMetadata",
    "DataPackNormalizerVersionError",
    "DataPackRuntimeVersionError",
    "DomainPack",
    "DomainRegistry",
    "EntityRecord",
    "EntityStore",
    "ExplainedResolution",
    "GenerationContext",
    "IncompatibleFeatureSchemaError",
    "IncompatibleVersionError",
    "InvalidKeyError",
    "LinkError",
    "LoadedDataPack",
    "MatchTier",
    "MissingModuleDependencyError",
    "ModuleConflictError",
    "ModuleRegistryError",
    "NoModulesInstalledError",
    "NormalizationProfile",
    "NormalizedText",
    "Query",
    "ReasonCode",
    "RefinementHint",
    "RegistryError",
    "ResolutionContext",
    "ResolutionError",
    "ResolutionResult",
    "ResolutionStatus",
    "RetrievalSummary",
    "SQLiteEntityStore",
    "ScoreSummary",
    "Severity",
    "TextNormalizer",
    "UnknownDomainError",
    "UnsupportedStoreError",
    "default_registry",
    "get_module_path",
    "get_pack_factory",
    "list_available_modules",
    "register_module",
    "register_pack_factory",
    "unregister_module",
]
